AGGREGATION = {
    "kpi_1": "sum",
    "kpi_2": "avg",
    "kpi_3": "min",
    "kpi_4": "max",
    "kpi_5": "sum",
    "kpi_6": "avg",
    "kpi_7": "min",
    "kpi_8": "max",
    "kpi_9": "sum",
    "kpi_10": "avg",
    "kpi_11": "min",
    "kpi_12": "max",
    "kpi_13": "sum",
    "kpi_14": "avg",
    "kpi_15": "min",
    "kpi_16": "max",
    "kpi_17": "sum",
    "kpi_18": "avg",
    "kpi_19": "min",
    "kpi_20": "max",
}